# Generated by Django 4.2.5 on 2023-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_no",
            field=models.CharField(max_length=50),
        ),
    ]
